kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: security-lab
nodes:
  - role: control-plane    # the K8s brain
  - role: worker           # runs your workloads
  - role: worker           # runs your workloads
networking:
  podSubnet: "10.244.0.0/16"      # IP range for pods
  serviceSubnet: "10.96.0.0/12"   # IP range for services
